name: Sample Test
on:
  workflow_dispatch:
    inputs:
      suiteName:
        type: choice
        description: 'Select Suite Name'
        required: false
        default: 'testNg_withDc.xml'
        options: ['testNg_withDc.xml', 'testNg_withDc1.xml', 'testNg_withDc3.xml']
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: Step1
        run: echo " This is Step 01"
        
      - name: Step2
        id: set-status
        run: echo "::set-output name=status::success"
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: job2 step1
        run: echo " this is Job2 Step1"
        
      - name: Get job1 status
        run: |
          JOB1_STATUS=${{ needs.job1.outputs.job1_status }}
          echo "Job1 status: $JOB1_STATUS"
