name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      suiteName:
        description: 'Test Suite Name'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Test
      run: mvn clean test -DsuteName=${{ github.event.inputs.suiteName}} 

    - name: Report Generation
      uses: actions/upload-artifact@v2
      with:
        name: testNgReport
        path: ./target/surefire-reports/index.html
